# Generated by Django 4.1.2 on 2022-10-09 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('hotel_app', '0002_remove_booking_hotel_remove_room_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.profile'),
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
